
name: 'personal'
version: '1.0.0'

profile: 'michael'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  staging:
    +materialized: view
    

seeds:
  mock_sources:
    +tags: ["local"]
    +enabled: "{{ target.name == 'dev' }}"

vars:
  'dbt_date:time_zone': 'UTC'
  # 7 hours (in milliseconds)
  sleep_goal: 25200000
