version: 2

models:
  - name: stg_notion__daily_habits
    description: "Unique daily habits from the Notion habit tracker."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
  - name: stg_notion__weekly_habits
    description: "Unique weekly habits from the Notion habit tracker."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
  - name: stg_notion__monthly_habits
    description: "Unique monthly habits from the Notion habit tracker."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique


sources:
  - name: notion
    description: "Source data from the Notion habit tracker."
    schema: "main"
    tables:
      - name: database_daily_habits
        identifier: notion__database_daily_habits
        description: "Raw habit entries from the daily notion database."
      - name: database_weekly_habits
        identifier: notion__database_weekly_habits
        description: "Raw habit entries from the weekly notion database."
      - name: database_monthly_habits
        identifier: notion__database_monthly_habits
        description: "Raw habit entries from the monthly notion database."
