version: 2

models:
  - name: stg_hubspot__companies
    description: "Companies from HubSpot CRM with tiering."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: tier
        description: "The ideal customer profile tier for a company."
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 3
              row_condition: "id is not null"
  - name: stg_hubspot__contacts
    description: "Contacts from HubSpot CRM with company mapping."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: company_id
        description: "The ID of the company associated with a contact."
        data_tests:
          - relationships:
              to: ref('stg_hubspot__companies')
              field: id
  - name: stg_hubspot__engagements
    description: "Engagements from HubSpot CRM with contact and company mapping."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: stg_hubspot__engagement_contacts
    description: "Junction table between engagements and contacts, created from companyIds."
    columns:
      - name: engagement_id
        description: "The ID of the engagement"
        data_tests:
          - relationships:
              to: ref('stg_hubspot__engagements')
              field: id
      - name: contact_id
        description: "The ID of the contact associated with the engagement"
        data_tests:
          - relationships:
              to: ref('stg_hubspot__contacts')
              field: id
  - name: stg_hubspot__engagement_companies
    description: "Junction table between engagements and companies, created from companyIds."
    columns:
      - name: engagement_id
        description: "The ID of the engagement"
        data_tests:
          - relationships:
              to: ref('stg_hubspot__engagements')
              field: id
      - name: company_id
        description: "The ID of the company associated with the engagement"
        data_tests:
          - relationships:
              to: ref('stg_hubspot__companies')
              field: id

sources:
  - name: hubspot
    description: "Source data from the HubSpot CRM."
    schema: "{{ env_var('RAW_SCHEMA', 'raw') }}"
    tables:
      - name: company
        identifier: hubspot__company
        description: "Raw company data from the HubSpot CRM."
        columns:
          - name: id
            description: "Primary key for the raw HubSpot company table."
            data_tests:
              - not_null
          - name: hs_ideal_customer_profile
            description: "The ideal customer profile tier for a company."
            data_tests:
              - accepted_values:
                  values: ["tier_1", "tier_2", "tier_3"]
      - name: contact
        identifier: hubspot__contact
        description: "Raw contact data from the HubSpot CRM."
        columns:
          - name: id
            description: "Primary key for the raw HubSpot contact table."
            data_tests:
              - not_null
          - name: associatedcompanyid
            description: "The ID of the company associated with a contact."
            data_tests:
              - relationships:
                  to: source('hubspot', 'company')
                  field: id
      - name: engagement
        identifier: hubspot__engagement
        description: "Raw engagement data from the HubSpot CRM."
        columns:
          - name: id
            description: "Primary key for the raw HubSpot engagement table."
            data_tests:
              - not_null
          - name: type
            description: "The type of HubSpot engagement."
            data_tests:
              - accepted_values:
                  values: ["CALL", "WHATS_APP", "MEETING", "SMS", "EMAIL", "LINKEDIN_MESSAGE"]
          - name: timestamp
            description: "The timestamp of the engagement."
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: '2023-01-01'
                  max_value: '2030-01-01'
          - name: contactIds
            description: "The IDs of the contact associated with an engagement."
            data_tests:
              - expect_column_array_length_to_be_between:
                  min_value: 1
                  max_value: 10
          - name: companyIds
            description: "The IDs of the company associated with an engagement."
            data_tests:
              - expect_column_array_length_to_be_between:
                  min_value: 1
                  max_value: 10
