"""
dlt_fitbit__health.py

DAGs to load data from FitBit using Web API.

OAuth2 access and refresh token can be generated by following this `tutorial`_.

.. _tutorial: https://dev.fitbit.com/build/reference/web-api/troubleshooting-guide/oauth2-tutorial/
"""

# Base
import json

# PyPI
import pendulum
import requests

# dlt
import dlt
from dlt.sources.rest_api import rest_api_source
from dlt.destinations import bigquery
from dlt.helpers.airflow_helper import PipelineTasksGroup
from dlt.sources.helpers.rest_client.paginators import (
    OffsetPaginator,
)

# Airflow hooks and operators
from airflow.models import DAG
from airflow.hooks.base import BaseHook

# Common custom tasks
from dags.michael.common.dlt_rest import HasMorePaginator
from dags.michael import DEFAULT_ARGS, RAW_SCHEMA, IS_TEST
from dags.michael.datasets import FITBIT_DS

# Connection IDs
FITBIT_CONN_ID = "fitbit_app"
BQ_CONN_ID = "bigquery_reporting"


def get_fitbit_token() -> str:

    # Request refreshed token
    connection = BaseHook.get_connection(FITBIT_CONN_ID)
    resp = requests.post(
        "https://api.fitbit.com/oauth2/token",
        auth=requests.auth.HTTPBasicAuth(connection.login, connection.password),
        data={
            "grant_type": "refresh_token",
            "refresh_token": connection.extra_dejson["refresh_token"],
        },
    )
    resp.raise_for_status()
    result = resp.json()

    # Update airflow connection details for next refresh
    connection.extra_dejson["access_token"] = result["access_token"]
    connection.extra_dejson["refresh_token"] = result["refresh_token"]
    connection.set_extra(json.dumps(connection.extra_dejson))

    return result["access_token"]


def get_fitbit_source(
    api_key: str,
    initial_date: str = "2024-01-01",
    is_incremental: bool = True,
):

    # Set default incremental dates
    # Should be overriden by Airflow data interval
    initial_dt = pendulum.parse(initial_date)
    if IS_TEST:
        end_dt = initial_dt.add(days=7)
    else:
        end_dt = pendulum.now("UTC")

    api_config = {
        "client": {
            "base_url": "https://api.fitbit.com/",
            "auth": {
                "type": "bearer",
                "token": api_key,
            },
            "headers": {
                "Content-Type": "application/json",
            },
        },
        "resource_defaults": {
            "write_disposition": "append",
        },
        "resources": [
            {
                "name": "fitbit__sleep",
                "endpoint": {
                    "path": "1.2/user/-/sleep/list.json",
                    "method": "GET",
                    "data_selector": "sleep",
                    "params": {
                        "sort": "asc",
                        "afterDate": "{incremental.start_value}",
                        "beforeDate": "{incremental.end_value}",
                    },
                    "incremental": {
                        "cursor_path": "dateOfSleep",
                        "initial_value": initial_date,
                        "end_value": end_dt.isoformat(),
                    },
                    "paginator": OffsetPaginator(
                        limit=100,
                    ),
                },
            },
            {
                "name": "fitbit__activities",
                "endpoint": {
                    "path": "1/user/-/activities/list.json",
                    "method": "GET",
                    "data_selector": "activities",
                    "params": {
                        "sort": "asc",
                        "afterDate": "{incremental.start_value}",
                        "beforeDate": "{incremental.end_value}",
                    },
                    "incremental": {
                        "cursor_path": "lastModified",
                        "initial_value": initial_date,
                        "end_value": end_dt.isoformat(),
                    },
                    "paginator": OffsetPaginator(
                        limit=100,
                    ),
                },
            },
        ],
    }

    return rest_api_source(api_config)


DAG_CONFIGS = [
    {
        "dag_id": "raw_fitbit__health__full",
        "schedule": "@once",
    },
    {
        "dag_id": "raw_fitbit__health__changed",
        "schedule": "@weekly",
    },
]
