version: 2

models:
  - name: int_habits_unpivoted
    description: "Combined list of daily, weekly, and monthly habits from the Notion habit tracker."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
    data_tests:
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list:
            - id
            - date