version: 2

models:
  - name: int_habits_unpivoted
    description: "Combined list of daily, weekly, and monthly habits from the Notion habit tracker."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null