"""
FitBit Web API source factory for dlt pipelines.

OAuth2 access and refresh token can be generated by following this `tutorial`_.

.. _tutorial: https://dev.fitbit.com/build/reference/web-api/troubleshooting-guide/oauth2-tutorial/

API Resources:

- `List Activities <https://dev.fitbit.com/build/reference/web-api/activity/get-activity-log-list/>`_  # noqa: E501
- `List Sleep <https://dev.fitbit.com/build/reference/web-api/sleep/get-sleep-log-list/>`_
"""

# Base
from typing import Any
from logging import getLogger

# PyPI
import requests
from google.cloud import secretmanager_v1
import google.auth

# dlt
import dlt
from dlt.sources.rest_api import rest_api_source
from dlt.sources.helpers.rest_client.paginators import OffsetPaginator

logger = getLogger(__name__)


def get_fitbit_token() -> str:
    """Get a fresh Fitbit API access token using the stored refresh token.

    This function requests a new access token from Fitbit's OAuth2 endpoint
    using the refresh token stored in DLT secrets. It also updates the
    refresh token in Google Secret Manager for future use.

    Returns:
        str: The new access token for Fitbit API requests.

    Raises:
        requests.HTTPError: If the token refresh request fails.
    """
    resp = requests.post(
        "https://api.fitbit.com/oauth2/token",
        auth=requests.auth.HTTPBasicAuth(
            dlt.secrets["sources.fitbit.client_id"],
            dlt.secrets["sources.fitbit.client_secret"],
        ),
        data={
            "grant_type": "refresh_token",
            "refresh_token": dlt.secrets["sources.fitbit.refresh_token"],
        },
        timeout=30,
    )
    resp.raise_for_status()
    result = resp.json()

    from pipelines import SECRET_STORE

    if SECRET_STORE == "google":
        _, project_id = google.auth.default()
        client = secretmanager_v1.SecretManagerServiceClient()
        parent = client.secret_path(project_id, "sources-fitbit-refresh_token")
        client.add_secret_version(
            request={
                "parent": parent,
                "payload": {"data": result["refresh_token"].encode("UTF-8")},
            }
        )
    else:
        from pipelines.common.utils import update_onepassword_item

        update_onepassword_item(
            item_name="fitbit",
            vault="reporting",
            field_updates={"refresh_token": result["refresh_token"]},
        )

    return result["access_token"]


def fitbit_source(
    api_key: str,
    initial_date: str = "1970-01-01",
    session=None,
    end_date: str | None = None,
):
    """Create a DLT source for Fitbit API data.

    This function configures and returns a DLT source for extracting sleep and
    activity data from the Fitbit Web API.

    Args:
        api_key (str): Fitbit API access token for authentication.
        initial_date (str, optional): Start date for data extraction in
            YYYY-MM-DD format. Defaults to `BASE_DATE`.
        session (requests.Session, optional): Optional requests session for
            HTTP calls. Defaults to None.
        end_date (str, optional): Optional end date for data extraction in
            YYYY-MM-DD format. Defaults to None.

    Returns:
        dlt.sources.rest_api.rest_api_source: dlt source configured for Fitbit
            data extraction.
    """
    api_config: dict[str, Any] = {
        "client": {
            "base_url": "https://api.fitbit.com/",
            "auth": {"type": "bearer", "token": api_key},
            "headers": {"Content-Type": "application/json"},
        },
        "resource_defaults": {"write_disposition": "append"},
        "resources": [
            {
                "name": "fitbit__sleep",
                "max_table_nesting": 1,
                "endpoint": {
                    "path": "1.2/user/-/sleep/list.json",
                    "method": "GET",
                    "data_selector": "sleep",
                    "params": {"sort": "asc", "afterDate": "{incremental.start_value}"},
                    "paginator": OffsetPaginator(
                        limit=100,
                        limit_param="limit",
                        offset_param="offset",
                        total_path=None,
                    ),
                    "incremental": {
                        "cursor_path": "dateOfSleep",
                        "initial_value": initial_date,
                        "end_value": end_date,
                    },
                },
            },
            {
                "name": "fitbit__activities",
                "max_table_nesting": 1,
                "columns": {"activity_level": {"data_type": "json"}},
                "endpoint": {
                    "path": "1/user/-/activities/list.json",
                    "method": "GET",
                    "data_selector": "activities",
                    "params": {"sort": "asc", "afterDate": "{incremental.start_value}"},
                    "paginator": OffsetPaginator(
                        limit=100,
                        limit_param="limit",
                        offset_param="offset",
                        total_path=None,
                    ),
                    "incremental": {
                        "cursor_path": "lastModified",
                        "initial_value": initial_date,
                        "end_value": end_date,
                        "convert": lambda d: d[:10],
                    },
                },
            },
        ],
    }
    if session:
        api_config["client"]["session"] = session

    return rest_api_source(api_config)
