version: 2

models:
  - name: stg_fitbit__sleep
    description: "Staging model for fitbit sleep data."
    columns:
      - name: log_id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique

sources:
  - name: fitbit
    description: "Source data from the fitbit activity tracker."
    schema: "main"
    tables:
      - name: sleep
        identifier: fitbit__sleep
        description: "Sleep data recorded in fitbit, often from Garmin."
        columns:
          - name: log_id
            description: "Primary key for the raw sleep table."
            data_tests:
              - not_null