CREATE TABLE IF NOT EXISTS `{{ BQ_HABIT_TABLE }}` (
    bq_id STRING DEFAULT GENERATE_UUID(),
    period STRING NOT NULL,
    page_id STRING NOT NULL,
    database_id STRING NOT NULL,
    date DATE NOT NULL,
    habit STRING NOT NULL,
    is_complete BOOLEAN NOT NULL,
    page_created TIMESTAMP NOT NULL,
    page_edited TIMESTAMP NOT NULL,
    bq_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);