#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "requirements.txt" ]; then
    echo "==> Installing python dependencies…"
    # Install dependencies with constraints
    pip install --upgrade pip
    pip install -r requirements-dev.txt   # -c constraints.txt
fi
