#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "requirements.txt" ]; then
    echo "==> Installing python dependencies…"
    # Install dependencies with constraints
    pip install -r requirements.txt -c constraints.txt
fi

