#!/bin/sh

# script/run: Start webserver and scheduler instances for the application.

set -e

echo "Running from $PWD"

# Load environment file and export variables
export AIRFLOW__CORE__EXECUTOR=LocalExecutor
export PYTHONPATH="/workspaces/personal-reporting"
export DBT_TARGET="dev"

# Start the application using honcho
honcho start