#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

# Run bootstrap script to install dependencies
script/bootstrap

echo "==> Setting up DB…"

# Reset Airflow database
airflow db reset --yes
airflow db migrate

# Create a basic admin user (local only)
airflow users create \
    --username admin \
    --password admin \
    --firstname local \
    --lastname admin \
    --role Admin \
    --email local@admin.org

if [ -f "config/connections.yml" ]; then
    echo "==> Setting up connections…"
    airflow connections import "config/connections.yml"
fi
