# Source credentials stored in Secret Manager as outlined:
# https://dlthub.com/docs/walkthroughs/add_credentials#retrieving-credentials-from-google-cloud-secret-manager

[providers]
enable_google_secrets=true

[providers.google_secrets]
only_secrets=true
only_toml_fragments=false
list_secrets=true

# Defined through environment using Application Default Credentials
# [providers.google_secrets.credentials]
# "project_id" = "<project_id>"
# "private_key" = "-----BEGIN PRIVATE KEY-----\n....\n-----END PRIVATE KEY-----\n"
# "client_email" = "....gserviceaccount.com"