version: 2

sources:
  - name: hubspot
    description: "Source data from the HubSpot CRM."
    schema: "{{ env_var('RAW_SCHEMA', 'raw') }}"
    tables:
      - name: companies
        identifier: hubspot__companies
        description: "Raw company data from the HubSpot CRM."
        columns:
          - name: id
            description: "Primary key for the raw HubSpot company table."
            data_type: integer
            data_tests:
              - not_null
          - name: properties__name
            description: "The name of the company."
            data_type: varchar
          - name: properties__createdate
            description: "The date the company was created."
            data_type: timestamp
          - name: properties__hs_lastmodifieddate
            description: "The date the company was last modified."
            data_type: timestamp
          - name: properties__hs_ideal_customer_profile
            description: "The ideal customer profile tier for a company."
            data_type: varchar
            data_tests:
              - accepted_values:
                  values: ["tier_1", "tier_2", "tier_3"]

      - name: contacts
        identifier: hubspot__contacts
        description: "Raw contact data from the HubSpot CRM."
        columns:
          - name: id
            description: "Primary key for the raw HubSpot contact table."
            data_type: integer
            data_tests:
              - not_null
          - name: properties__associatedcompanyid
            description: "The ID of the company associated with a contact."
            data_type: integer
            data_tests:
              - relationships:
                  to: source('hubspot', 'companies')
                  field: id
          - name: properties__email
            description: "The email address of the contact."
            data_type: varchar
          - name: properties__firstname
            description: "The first name of the contact."
            data_type: varchar
          - name: properties__lastname
            description: "The last name of the contact."
            data_type: varchar
          - name: properties__createdate
            description: "The date the contact was created."
            data_type: timestamp
          - name: properties__lastmodifieddate
            description: "The date the contact was last modified."
            data_type: timestamp

      - name: engagements
        identifier: hubspot__engagements
        description: "Raw engagement data from the HubSpot CRM."
        columns:
          - name: engagement__id
            description: "Primary key for the raw HubSpot engagement table."
            data_type: integer
            data_tests:
              - not_null
          - name: engagement__type
            description: "The type of HubSpot engagement."
            data_type: varchar
            data_tests:
              - accepted_values:
                  values: ["CALL", "WHATS_APP", "MEETING", "SMS", "EMAIL", "LINKEDIN_MESSAGE"]
          - name: engagement__timestamp
            description: "The timestamp of the engagement."
            data_type: timestamp
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: "timestamp '2023-01-01'"
                  max_value: "timestamp '2030-01-01'"
          - name: associations__contact_ids
            description: "The IDs of the contact associated with an engagement."
            data_type: varchar
            data_tests:
              - expect_column_array_length_to_be_between:
                  min_value: 0
                  max_value: 10
                  config:
                    enabled: "{{ target.type != 'duckdb' }}"
          - name: associations__company_ids
            description: "The IDs of the company associated with an engagement."
            data_type: varchar
            data_tests:
              - expect_column_array_length_to_be_between:
                  min_value: 0
                  max_value: 10
                  config:
                    enabled: "{{ target.type != 'duckdb' }}"
