version: 2

models:
  - name: stg_notion__daily_habits
    description: "Unique daily habits from the Notion habit tracker."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
  - name: stg_notion__weekly_habits
    description: "Unique weekly habits from the Notion habit tracker."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
  - name: stg_notion__monthly_habits
    description: "Unique monthly habits from the Notion habit tracker."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique


sources:
  - name: notion
    description: "Source data from the Notion habit tracker."
    schema: "{{ env_var('RAW_SCHEMA', 'raw') }}"
    tables:
      - name: daily_habit
        identifier: notion__daily_habit
        description: "Raw habit entries from the daily notion database."
        columns:
          - name: id
            description: "Primary key for the raw daily habits table."
            data_tests:
              - not_null
      - name: weekly_habit
        identifier: notion__weekly_habit
        description: "Raw habit entries from the weekly notion database."
        columns:
          - name: id
            description: "Primary key for the raw weekly habits table."
            data_tests:
              - not_null
      - name: monthly_habit
        identifier: notion__monthly_habit
        description: "Raw habit entries from the monthly notion database."
        columns:
          - name: id
            description: "Primary key for the raw monthly habits table."
            data_tests:
              - not_null
