name: Notion Pipeline
on:
  schedule:
    - cron: '0 9 * * 0'  # Weekly on Sundays at 9 AM UTC
  workflow_dispatch:
    inputs:
      force_full_refresh:
        description: 'Force full refresh'
        required: false
        default: 'false'
        type: boolean

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: $HOME/sa_key.json
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install pipenv
        run: |
          pip install pipenv
          
      - name: Install dependencies
        run: |
          make install
          
      - name: Write keyfile
        run: |
          echo ${{ secrets.GCP_SVC_KEY }} > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Run Notion Pipeline
        env:
          FORCE_FULL_REFRESH: ${{ inputs.force_full_refresh }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SVC_KEY }}
          RUNTIME__LOG_LEVEL: "INFO"
        run: |
          pipenv run python -m pipelines.notion
          
      - name: Remove keyfile
        if: always()
        run: |
          rm $GOOGLE_APPLICATION_CREDENTIALS

      - name: Upload dlt state files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notion-pipeline-state
          path: |
            ~/.dlt/**/state.json
          retention-days: 7 