name: Pipeline Tests
on:
  pull_request:
    paths:
      - 'pipelines/**'
      - 'tests/**'
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'Makefile'
  push:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - 'tests/**'

jobs:
  test-pipelines:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa_key.json" >> $GITHUB_ENV
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install pipenv
        run: |
          pip install pipenv
          
      - name: Install dependencies
        run: |
          make install
          
      - name: Write keyfile
        run: |
          cat << 'EOF' > $GOOGLE_APPLICATION_CREDENTIALS
          ${{ secrets.GCP_SVC_KEY }}
          EOF

      - name: Run tests
        env:
          RUNTIME__LOG_LEVEL: "INFO"
        run: |
          make test-all

      - name: Remove keyfile
        if: always()
        run: |
          rm $GOOGLE_APPLICATION_CREDENTIALS
          
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            htmlcov/
            .coverage
          retention-days: 30