name: test dbt transformations
on:
  pull_request:
    branches:
      - main
    paths:
      - 'dbt/**/*.sql'
      - 'dbt/**/*.yml'
      - 'dbt/**/*.csv'
  push:
    branches:
      - main
    paths:
      - 'dbt/**'
      - 'dbt/**/*.yml'
      - 'dbt/**/*.csv'

permissions:
  contents: 'read'

jobs:
  test_dbt:
    runs-on: ubuntu-latest
    env:
      DBT_PROJECT_DIR: dbt
      DBT_PROFILES_DIR: dbt
    steps:
      - name: check out code
        uses: actions/checkout@v5

      - name: set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          version: 'latest'
          enable-cache: true

      - name: set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: install dependencies
        run: |
          make install

      - name: install dbt dependencies
        run: |
          uv run dbt deps --project-dir dbt --profiles-dir dbt

      - name: run local build
        run: |
          uv run dbt build --project-dir dbt --profiles-dir dbt --target mock

      - name: generate docs and catalog
        run: |
          uv run dbt docs generate --project-dir dbt --profiles-dir dbt --static --target mock

      - name: run dbt-bouncer checks
        run: |
          uv run dbt-bouncer --config-file dbt/dbt-bouncer.yml
